  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: resensa
        POSTGRES_PASSWORD: 1423
      volumes:
        - postgres_volume:/app/files
      user: postgres
      ports:
        - "5432:5432"
      networks:
        - default_network
      healthcheck:
        test: [ "CMD", "pg_isready", "-U", "postgres" ]
        interval: 10s
        timeout: 5s
        retries: 10
    app:
      build: .
      environment:
        BOT_ID: 7596705272:AAEMTxUss6MarU3qpSXUyM8DTOiGdmhXtOc
        CHAT_ID: -1002335074227
        DATABASE_URL: "postgresql+asyncpg://postgres:1423@postgres:5432/resensa"  # Critical!
      networks:
        - default_network
      volumes:
        - fastapi_server_volume:/app/files
      ports:
        - "8002:8002"
      depends_on:
        postgres:
          condition: service_healthy


  volumes:
    postgres_volume:
    fastapi_server_volume:

  networks:
    default_network:
      driver: bridge